version: "3.8"

services:
  # MySQL Database Service
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6613:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laraveluser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  # PHP-FPM Service
  app:
    image: chandrawira/laravel-app:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-laraveluser}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
    networks:
      - app-network

  # Nginx Web Server Service
  nginx:
    image: chandrawira/nginx:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - "8088:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network

# Define Docker volumes
volumes:
  db-data:

networks:
  app-network:
    driver: overlay
