version: "3.8"

services:
  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: laravel_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306:6603"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret} # Use environment variable or default to secret
      MYSQL_DATABASE: ${DB_DATABASE:-laravel} # Use environment variable or default to laravel
      MYSQL_USER: ${DB_USERNAME:-laraveluser}  # Use environment variable or default to laraveluser
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}   # Use environment variable or default to secret
    volumes:
      - db-data:/var/lib/mysql # Changed to Docker volume
    networks:
      - app-network

  # PHP-FPM Service
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USERNAME:-laraveluser}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
      # Add any other environment variables your Laravel app needs here
      # For example:
      # APP_ENV: local
      # APP_DEBUG: true
    networks:
      - app-network

  # Nginx Web Server Service
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:8088"
    volumes:
      - ./www:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network

# Define Docker volumes
volumes:
  db-data: # Define the volume for MySQL data

networks:
  app-network:
    driver: bridge
